require:
  - './lib/rubocop-on-rbs'

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rubocop-on-rbs.rb

Lint/AssignmentInCondition:
  Enabled: false

Style:
  Enabled: false

Metrics:
  Enabled: false
