plugins:
  - rubocop-on-rbs

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rubocop-on-rbs.rb

Layout/LeadingCommentSpace:
    AllowRBSInlineAnnotation: true

Lint/AssignmentInCondition:
  Enabled: false

Style:
  AutoCorrect: false
  Severity: info

Metrics:
  Enabled: false
