# frozen_string_literal: true

require_relative 'rbs_inline/lint/ambiguous_keyword_argument_key'
require_relative 'rbs_inline/lint/duplicate_overload'
require_relative 'rbs_inline/lint/literal_intersection'
require_relative 'rbs_inline/lint/new_returns_void'
require_relative 'rbs_inline/lint/rest_keyword_hash'
require_relative 'rbs_inline/lint/syntax'
require_relative 'rbs_inline/lint/unused_annotation'
require_relative 'rbs_inline/lint/unused_overload_type_params'

require_relative 'rbs_inline/style/block_return_boolish'
require_relative 'rbs_inline/style/class_with_singleton'
require_relative 'rbs_inline/style/classic_type'
require_relative 'rbs_inline/style/duplicated_type'
require_relative 'rbs_inline/style/empty_argument'
require_relative 'rbs_inline/style/initialize_return_type'
require_relative 'rbs_inline/style/instance_with_instance'
require_relative 'rbs_inline/style/optional_nil'
require_relative 'rbs_inline/style/redundant_parentheses'
require_relative 'rbs_inline/style/true_false'
