inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  Include:
    - '**/*.rbs'

Lint:
  Exclude:
    - '**/*.rbs'

Style:
  Exclude:
    - '**/*.rbs'

# RBS

RBS:
  Enabled: true
  Include:
    - '**/*.rbs'

## RBS/Layout

RBS/Layout:
  Enabled: true

RBS/Layout/CommentIndentation:
  Description: 'Use 2 spaces for comment indentation'
  Enabled: true

RBS/Layout/EmptyLineAroundOverloads:
  Description: 'No empty line between overload'
  Enabled: true

RBS/Layout/EndAlignment:
  Description: 'Align `end` keyword'
  Enabled: true

RBS/Layout/ExtraSpacing:
  Description: 'Remove extra spacing'
  Enabled: true

RBS/Layout/IndentationWidth:
  Description: 'Use 2 spaces for indentation'
  Enabled: true

RBS/Layout/OverloadIndentation:
  Description: 'Indent overload method'
  Enabled: true

RBS/Layout/SpaceAroundArrow:
  Description: 'Use space around `->`'
  Enabled: true

RBS/Layout/SpaceAroundBraces:
  Description: 'Use space around `{}`'
  Enabled: true

RBS/Layout/SpaceBeforeColon:
  Description: 'Use space before `:`'
  Enabled: true

RBS/Layout/SpaceBeforeOverload:
  Description: 'Use space before overload method'
  Enabled: true

RBS/Layout/TrailingWhitespace:
  Description: 'Remove trailing whitespace'
  Enabled: true

## RBS/Lint

RBS/Lint:
  Enabled: true

RBS/Lint/DuplicateOverload:
  Severity: warning
  Description: 'Checks that there are no repeated overload bodies'
  Enabled: true

RBS/Lint/UselessOverloadTypeParams:
  Severity: warning
  Description: 'Check redundant overload type params'
  Enabled: true

RBS/Lint/Syntax:
  Severity: fatal
  Description: 'Check RBS syntax'
  Enabled: true

RBS/Lint/WillSyntaxError:
  Severity: warning
  Description: 'Check RBS will syntax error'
  Enabled: true

## RBS/Style

RBS/Style:
  Enabled: true

RBS/Style/BlockReturnBoolish:
  Description: 'Use `bool` for block return type'
  Enabled: true

RBS/Style/ClassicType:
  Description: 'Use simple type'
  Enabled: true

RBS/Style/DuplicatedType:
  Description: 'Check duplicated type'
  Enabled: true

RBS/Style/InitializeReturnType:
  Description: 'Use `void` for initialize method'
  Enabled: true

RBS/Style/OptionalNil:
  Description: 'Use nil instead of nil?'
  Enabled: true

RBS/Style/TrueFalse:
  Description: 'Use bool instead of true | false'
  Enabled: true
