module RuboCop
  module Cop
    module RBS
      module Layout
        # @example default
        #   # bad
        #   def   foo:   ()   ->   void
        #
        #   # good
        #   def foo: () -> void
        class ExtraSpacing < RuboCop::RBS::CopBase
          extend AutoCorrector

          MSG: String

          def aligned_locations: () -> ::Set[Integer]
        end
      end
    end
  end
end
