name: Steep

# TODO: Re-enable triggers
# on:
#   push:
#     branches:
#       - main
#
#   pull_request:
#     types:
#       - opened
#       - synchronize
#       - reopened
#       - ready_for_review
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v7.0.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    - name: Run the RuboCop
      run: |
        bundle exec rbs collection install
        bundle exec steep check --jobs 2
